language: node_js
node_js:
  - "15"
dist: trusty
services:
  - xvfb
  - mongodb
  - redis-server
env:
 - NODE_ENV=ci
 - PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - xvfb run make test